### PR TITLE
Added PHP8 support

### PR DESCRIPTION
**Pull request by boboldehampsink**

### CODE REVIEW

**Comment by boboldehampsink** [comment]
@bertoost :wave:

**Comment by bertoost** [comment]
I want to test it on PHP8 first. Don't have time yet to create a local environment. Thanks any way for this.

**Comment by boboldehampsink** [comment]
@bertoost any news on this? It's been 3 weeks. I have been using it in production for a while now.

**Comment by boboldehampsink** [comment]
Any news yet?

**Comment by boboldehampsink** [comment]
@bertoost bump

**Comment by bertoost** [comment]
That does not work with me @boboldehampsink .. I am not able to run Craft in PHP8 at the moment. Missing extensions or configurations. Therefore is PHP8 way to new, so not high priority at the moment.
When I am able to, I will try this out.

**Comment by boboldehampsink** [comment]
@bertoost you're not the only one running this plugin ;-) Like I said, I have been running this in production for a few months on PHP 8 now, it is good to go.

**Comment by bertoost** [comment]
I know. Luckely I did not do it for myself..
But I am running locally with Docker and I am not able to complete my image for PHP8.0 and Craft. I can't get some extensions to work. Like ImageMagick is now the only one which is not working. Therefore not needed for this.
I have plans to fix this PR this weekend.

**Comment by bertoost** [comment]
Hope you (and others) are happy ;-) hehe

**Comment by boboldehampsink** [comment]
Thanks bert and sorry for giving you a hard time :-)

**Pull request merged**
